#include "ilcplex/ilocplex.h"
#include <iostream>
//#include <vector>
#include <boost/graph/adjacency_list.hpp>
//#include <boost/graph/depth_first_search.hpp>
//#include <boost/graph/breadth_first_search.hpp>
//#include <boost/graph/named_function_params.hpp>
//#include <boost/graph/visitors.hpp>
//#include <boost/array.hpp>
#include <boost/graph/graphviz.hpp>
#include <utility>
#include <map>
//#include <stdlib.h>
//#include <stdio.h>
//#include <windows.h>
//#include <atlstr.h>
//#include "graph_viz_prop_writer.h"
#include <chrono>

